---
title: "Homework 6"
author: "Xinyin Miao (xm2356)"
date: "2025-11-22"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)   
library(broom)     
library(purrr)  
```

# Problem 1

```{r}
homicides <- readr::read_csv("data/homicide-data.csv") |>
  clean_names() |>
  mutate(
    city_state = str_c(city, ", ", state),
    solved = if_else(disposition == "Closed by arrest", 1L, 0L),
    victim_sex  = na_if(victim_sex,  "Unknown"),
    victim_race = na_if(victim_race, "Unknown"),
    victim_age = ifelse(victim_age %in% c("Unknown", ""), NA, victim_age),
    victim_age = as.numeric(victim_age)
    ) |>
  filter(!city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
         victim_race %in% c("White", "Black")
         ) |>
  mutate(
    victim_sex  = factor(victim_sex,  levels = c("Female", "Male")),
    victim_race = factor(victim_race, levels = c("White", "Black"))
  )

```

## For Baltimore,MD
```{r}
baltimore <-
  homicides |>
  filter(city_state == "Baltimore, MD")

baltimore_glm <-
  glm(
    solved ~ victim_age + victim_sex + victim_race,
    data   = baltimore,
    family = binomial()
  )

```

```{r}
baltimore_results <-
  baltimore_glm |>
  tidy(
    conf.int     = TRUE,
    exponentiate = TRUE 
  )

baltimore_male_female_or <-
  baltimore_results |>
  filter(term == "victim_sexMale") |>
  select(term, estimate, conf.low, conf.high)

baltimore_male_female_or |> 
  knitr::kable(digits = 4)

# the estimate and CI of the adjusted odds ratio for solving homicides comparing male to female victims keeping all other variables fixed

```

## For each of the cities
```{r}
city_results <-
  homicides |>
  nest(data = -city_state) |>
  mutate(
    model = map(data, \(df) glm( solved ~ victim_age + victim_sex + victim_race,  data   = df, family = binomial())
    ),
    tidied = map(model, \(m) tidy(m,
        conf.int     = TRUE,
        exponentiate = TRUE
      )
    )
  ) |>
  select(city_state, tidied) |>
  unnest(tidied) |>
  filter(term == "victim_sexMale") |> 
  select(city_state, estimate, conf.low, conf.high) |> 
  arrange(desc(estimate))

city_results |> 
  knitr::kable(digits = 4)

```













